### ISSUE TITLE
v0.2.0 gemspec not in master

### ISSUE THREAD

**Issue by jqr** [brandonweiss/faraday-request-timer#6]
It looks like the v0.2.0 tag was pushed with 9e04772450e9fb4a3c773684ecfdf91ba511b092 but that commit hasn't made it into master.

This looks accidental and makes forked repos a little more annoying to maintain. Could you bring 9e04772450e9fb4a3c773684ecfdf91ba511b092 into master?

**Comment by brandonweiss** [comment]
Sorry about that! I think I just forgot to push 🤦‍♂ It should be fixed now!
